require: rubocop-gitlab-security

Layout/LineLength:
  Max: 200

Layout/ParameterAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/NumericLiteralPrefix:
    EnforcedOctalStyle: zero_only

Style/StringLiterals:
  Enabled: false

AllCops:
  Exclude:
    - 'third-party/**/*'
